sudo: false

branches:
  only:
    - master
    - develop

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2

cache:
  directories:
    - $HOME/.stack

before_install:
  - export PATH=/opt/ghc/7.10.2/bin:$PATH

install:
  - stack --no-terminal --no-install-ghc test --only-snapshot

script:
  - stack --no-terminal --no-install-ghc test
